{% set version = "4.12.2" %}

package:
  name: libitk
  version: "{{version}}"

source:
  url: https://github.com/InsightSoftwareConsortium/ITK/archive/v{{version}}.tar.gz
  sha256: 34c7312cfb54b3dbfc8591f3c2164113d628069115d7655d20160f028590ed18

build:
    number: 0
    skip: True   # [win and py36]
    features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - toolchain
    - cmake    >=3.3
    - ninja
    - expat    2.1.*
    - hdf5     1.8.18|1.8.18.*  # [not win]
    - jpeg     9*
    - libtiff  4.0.*
    - libpng   >=1.6.27,<1.7
    - zlib     1.2.*
    - python   # [win]
    - vc 9     # [win and py27]
    - vc 10    # [win and py34]
    - vc 14    # [win and py>=35]
  run:
    - expat    2.1.*
    - hdf5     1.8.18|1.8.18.*  # [not win]
    - jpeg     9*
    - libtiff  4.0.*
    - libpng   >=1.6.27,<1.7
    - zlib     1.2.*
    - vc 9   # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  requires:
    - cmake
  files:
    - example
  commands:
    - test -d $PREFIX/include/ITK*                        # [not win]
    - if not exist %LIBRARY_INC%\\ITK* exit 1             # [win]
    - itkTestDriver -- echo "Runtime ITK OK"
    - cmake -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}" ./example  # [not win]
    - cmake --build . --config Release                                  # [not win]

about:
  home: http://www.itk.org
  license: Apache 2.0
  license_file: LICENSE
  summary: Runtime libraries and header files for the Insight Toolkit for segmentation and registration.

extra:
    recipe-maintainers:
      - blowekamp
      - bluescarni
