{% set version = "5.1.2" %}

package:
  name: libitk
  version: {{ version }}

source:
  url: https://github.com/InsightSoftwareConsortium/ITK/archive/v{{ version }}.tar.gz
  sha256: 651284ce6f68e8bd31db176a6b53f5679209a8ed5b6b5480c3591d66c6e10b60

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake    >=3.3
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - expat                     # [not win]
    - fftw
    - hdf5                      # [not win]
    - jpeg
    - libtiff
    - libpng
    - eigen
    - zlib                      # [not win]

outputs:
  - name: libitk
    script: libitk_install.sh  # [not win]
    script: libitk_install.bat  # [win]
    requirements:
      run:
        - expat                     # [not win]
        - fftw
        - hdf5                      # [not win]
        - jpeg
        - libtiff
        - libpng
        - eigen
        - zlib                      # [not win]

    test:
      files:
        - ITK-JPEG.jpg
      commands:
        - test -d $PREFIX/include/ITK*                        # [not win]
        - if not exist %LIBRARY_INC%\\ITK* exit 1             # [win]
        - itkTestDriver -- echo "Runtime ITK OK"
        - itkTestDriver --no-process --compare-MD5 ITK-JPEG.jpg 959e1682d19026fc62cfbdc140df31da
  - name: libitk-devel
    script: libitk-devel_install.sh  # [not win]
    script: libitk-devel_install.bat  # [win]
    requirements:
      build:
        - cmake
      host:
        - {{ pin_subpackage("libitk", exact=True) }}
      run:
        - {{ pin_subpackage("libitk", exact=True) }}

    test:
      requires:
        - cmake
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - ninja  # [win]
      files:
        - example
      commands:
        - cmake -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}" ./example  # [not win]
        - cmake -G Ninja -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=%PREFIX%" example     # [win]
        - cmake --build . --config Release                                  # [not win]

about:
  home: http://www.itk.org
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  summary: Runtime libraries and header files for the Insight Toolkit for segmentation and registration.

extra:
  recipe-maintainers:
    - blowekamp
    - bluescarni
