{% set version = "4.13.0" %}

package:
  name: libitk
  version: "{{version}}"

source:
  url: https://github.com/InsightSoftwareConsortium/ITK/archive/v{{version}}.tar.gz
  sha256: 37122d65b89699df33f34e0859f1e7adf5a6222060dc1c47383ff7aa4531223a

build:
    number: 0

requirements:
  build:
    - cmake    >=3.3
    - ninja
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - expat
    - hdf5                      # [not win]
    - jpeg
    - libtiff
    - libpng
    - zlib
  run:
    - expat
    - hdf5                      # [not win]
    - jpeg
    - libtiff
    - libpng
    - zlib

test:
  requires:
    - cmake
  files:
    - example
  commands:
    - test -d $PREFIX/include/ITK*                        # [not win]
    - if not exist %LIBRARY_INC%\\ITK* exit 1             # [win]
    - itkTestDriver -- echo "Runtime ITK OK"
    - cmake -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}" ./example  # [not win]
    - cmake --build . --config Release                                  # [not win]

about:
  home: http://www.itk.org
  license: Apache 2.0
  license_file: LICENSE
  summary: Runtime libraries and header files for the Insight Toolkit for segmentation and registration.

extra:
    recipe-maintainers:
      - blowekamp
      - bluescarni
