build_platform:
  linux_ppc64le: linux_ppc64le
  linux_aarch64: linux_aarch64
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
test_on_native_only: true
linux_ppc64le:
  enabled: True
linux_aarch64:
  enabled: True
