build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
linux_aarch64:
  enabled: True
linux_ppc64le:
  enabled: False
provider:
  linux_aarch64: default
test: native_and_emulated
test_on_native_only: true
conda_build:
  pkg_format: '2'
